[env:jc4827w543]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Flash / PSRAM
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 4MB
board_build.partitions = no_ota.csv

; USB CDC (used for serial monitor + Web Serial flashing)
build_flags =
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DCORE_DEBUG_LEVEL=0
  -DLV_CONF_INCLUDE_SIMPLE
  -DLGFX_USE_QSPI
  -I src
  -I .

lib_deps =
  lovyan03/LovyanGFX @ >=1.2.7
  lvgl/lvgl @ 8.3.11
  bblanchon/ArduinoJson @ ^7.0.0
  https://github.com/mmMicky/TouchLib.git

lib_ldf_mode = deep+
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Build merged binary for web installer
extra_scripts = post:scripts/merge_bin.py
